#!/usr/bin/env bash

cp ~/.i3/config ./rc/i3_config
cp ~/.i3/status ./rc/i3_status
cp ~/.vimrc ./rc/vimrc
cp ~/.pryrc ./rc/pryrc
cp ~/.zshrc ./rc/zshrc
cp ~/.dircolors ./rc/dircolors
cp ~/.Xmodmap ./rc/xmodmap
