set nocompatible
syntax on
filetype off

set mouse=a
set number
set hlsearch
set expandtab
set synmaxcol=250
set guifont=Ubuntu\ Mono\ 24
set clipboard=unnamedplus " Yank and paste to the system clipboard

if &term =~ '256color'
  " Disable Background Color Erase (BCE) so that color schemes
  " work properly when Vim is used inside tmux and GNU screen.
  " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif

" automatically resize window
au VimResized * exe "normal! \<c-w>="

" _ backups
set undodir=~/.vim/tmp/undo//     " undo files
set undofile
set undolevels=3000
set undoreload=10000
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup
set noswapfile

inoremap jk <Esc>
vnoremap jk <Esc>

let mapleader=" "

" Save current file, reload vim config, and restart i3.
map <Leader>r :w<CR>:so ~/.vimrc<CR>:call system("i3-msg restart")<CR>
map <Leader>b :BundleInstall<CR>

" Fast up / down
nnoremap <S-j> <C-d>
nnoremap <S-k> <C-u>

" Easy splitted window navigation
nnoremap <S-h> <C-w>h
nnoremap <S-l> <C-w>l

nnoremap <Leader>d :NERDTreeFind<CR>
map <Leader>f <plug>NERDTreeTabsToggle<CR>

" Wicked Tab management
map <Leader>j :tabp<CR>
map <Leader>k :tabn<CR>
map <Leader>t :tabnew<CR>

map <Leader>q :q<CR>
map <Leader>s :w<CR>
map <Leader>w :w<CR>

map <Leader>g :Goyo<CR>
autocmd User GoyoEnter :set linebreak
autocmd User GoyoEnter Limelight
autocmd User GoyoLeave :set linebreak!
autocmd User GoyoLeave Limelight!

" Paste last line of pry history to buffer
nmap <Leader>ph :<c-u>let pc = (v:count1 ? v:count1 : 1)<cr>:read !tail -<c-r>=pc<cr> ~/.pry_history<cr>:.-<c-r>=pc-1<cr>:norm <c-r>=pc<cr>==<cr>

" Begin Vundle Config
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle (need this for the rest)
Bundle 'gmarik/vundle'

Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdtree'
Bundle 'jistr/vim-nerdtree-tabs'

Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-fireplace'
Bundle 'tpope/vim-classpath'
Bundle 'tpope/vim-surround'
Bundle 'itchyny/lightline.vim'
Bundle 'junegunn/goyo.vim'
Bundle 'junegunn/limelight.vim'
Bundle 'junegunn/rainbow_parentheses.vim'

Bundle 'digitaltoad/vim-jade'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-liquid'
Bundle 'tkztmk/vim-vala'
Bundle 'exu/pgsql.vim'
Bundle 'guns/vim-clojure-static'
Bundle 'elixir-lang/vim-elixir'
Bundle 'kchmck/vim-coffee-script'

Bundle 'mileszs/ack.vim'
Bundle 'tpope/vim-endwise'
Bundle 'vim-scripts/omlet.vim'
Bundle 'majutsushi/tagbar'
Bundle 'airblade/vim-gitgutter'

" Themes
Bundle 'sjl/badwolf'
Bundle 'flazz/vim-colorschemes'
Bundle 'endel/vim-github-colorscheme'
Bundle 'altercation/vim-colors-solarized'
Bundle 'chriskempson/base16-vim'
Bundle 'tomasr/molokai'
Bundle 'junegunn/seoul256.vim'
let g:seoul256_background = 234
colo seoul256

" Some OCAML stuff
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
execute "set rtp+=" . g:opamshare . "/merlin/vimbufsync"

" Indent Settings
Bundle 'nathanaelkane/vim-indent-guides'
set ts=2 sw=2 et
let g:indent_guides_start_level = 2
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0 
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black    ctermbg=235 
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=darkgrey ctermbg=236 

Bundle 'michaeljsmith/vim-indent-object'
let g:indentobject_meaningful_indentation = ["haml", "sass", "python", "yaml", "markdown"]

" CtrlP 
Bundle 'kien/ctrlp.vim'
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_match_window_bottom = 0 " Show at top of window
let g:ctrlp_jump_to_buffer = 'Et' " Jump to tab AND buffer if already open
let g:ctrlp_split_window = 1 " <CR> = New Tab
let g:ctrlp_open_new_file = 't' " Open newly created files in a new tab
let g:ctrlp_open_multiple_files = 't' " Open multiple files in new tabs
let g:ctrlp_show_hidden = 1 " Index hidden files
set wildignore+=*/public/uploads/*

" Only show cursorline in the current window and in normal mode.
augroup cline
    au!
    au WinLeave * set nocursorline
    au WinEnter * set cursorline
    au InsertEnter * set nocursorline
    au InsertLeave * set cursorline
augroup END

" File associations
au BufNewFile,BufRead *.sql set filetype=pgsql
au BufNewFile,BufRead *.ejs* set filetype=html
au BufNewFile,BufRead *.html.slim set filetype=slim
au BufNewFile,BufRead *.cljs set filetype=clojure
au BufNewFile,BufRead *.pde set filetype=java
au BufNewFile,BufRead *.hl set filetype=clojure
au BufNewFile,BufRead *.liso set filetype=julia
au BufNewFile,BufRead *.vala set filetype=cs
au BufNewFile,BufRead *.odocl set filetype=ocaml
au BufNewFile,BufRead *.topscript set filetype=ocaml
au BufNewFile,BufRead *.rawscript set filetype=ocaml
au BufNewFile,BufRead .pryrc set filetype=ruby
au BufNewFile,BufRead *.routes set filetype=erlang
au BufNewFile,BufRead rebar.config set filetype=erlang
au BufRead,BufNewFile schema.rb set filetype=txt

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
